version: 2
jobs:
  build:
    working_directory: ~/tebukuro-client
    docker:
      - image: circleci/node:8.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn test
